# Generated by Django 3.1.4 on 2020-12-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalinfo',
            name='AirScore1',
            field=models.PositiveIntegerField(null=True, verbose_name='AirScore1'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='AirScore2',
            field=models.PositiveIntegerField(null=True, verbose_name='AirScore2'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='AirVersion',
            field=models.PositiveIntegerField(null=True, verbose_name='AirVersion'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='CTTime',
            field=models.PositiveIntegerField(null=True, verbose_name='CTTime'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='EarnedCoins',
            field=models.PositiveIntegerField(null=True, verbose_name='EarnedCoins'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='ExpandLevel',
            field=models.PositiveIntegerField(null=True, verbose_name='ExpandLevel'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='FVer',
            field=models.PositiveIntegerField(null=True, verbose_name='FVer'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='GHash',
            field=models.BigIntegerField(null=True, verbose_name='GHash'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='PrevGCID',
            field=models.CharField(max_length=50, null=True, verbose_name='PrevGCID'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='SBCTime',
            field=models.BigIntegerField(null=True, verbose_name='SBCTime'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='SCOrders',
            field=models.BigIntegerField(null=True, verbose_name='SCOrders'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='SCTime',
            field=models.BigIntegerField(null=True, verbose_name='SCTime'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='VCheckTime',
            field=models.BigIntegerField(null=True, verbose_name='VCheckTime'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='WHUdup',
            field=models.PositiveIntegerField(null=True, verbose_name='WHUdup'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='changeVarTimestamp',
            field=models.BigIntegerField(null=True, verbose_name='changeVarTimestamp'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='dayInGame',
            field=models.PositiveIntegerField(null=True, verbose_name='dayInGame'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='earnedCash',
            field=models.PositiveIntegerField(null=True, verbose_name='earnedCash'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='experience',
            field=models.BigIntegerField(null=True, verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='factoryTime',
            field=models.BigIntegerField(null=True, verbose_name='factoryTime'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='gameId',
            field=models.CharField(max_length=50, null=True, verbose_name='gameId'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='gameStartDate',
            field=models.BigIntegerField(null=True, verbose_name='gameStartDate'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='lastVisitDay',
            field=models.PositiveIntegerField(null=True, verbose_name='lastVisitDay'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='lastVisitDayEBR',
            field=models.PositiveIntegerField(null=True, verbose_name='lastVisitDayEBR'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='lastVisitSaleDay',
            field=models.PositiveIntegerField(null=True, verbose_name='lastVisitSaleDay'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='levelup',
            field=models.PositiveIntegerField(null=True, verbose_name='levelup'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='maxResidents',
            field=models.PositiveIntegerField(null=True, verbose_name='maxResidents'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='money',
            field=models.PositiveIntegerField(null=True, verbose_name='money'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='moneyCash',
            field=models.PositiveIntegerField(null=True, verbose_name='moneyCash'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='orderSeq',
            field=models.PositiveIntegerField(null=True, verbose_name='orderSeq'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='saveGlobalTime',
            field=models.BigIntegerField(null=True, verbose_name='saveGlobalTime'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='timeInGame',
            field=models.FloatField(null=True, verbose_name='timeInGame'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='townName',
            field=models.CharField(max_length=50, null=True, verbose_name='townName'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='var_hex',
            field=models.CharField(max_length=50, null=True, verbose_name='hex'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='var_hex2',
            field=models.CharField(max_length=50, null=True, verbose_name='hex2'),
        ),
    ]
