"""
Django settings for py_township project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent
ROOT_DIR = BASE_DIR.parent
EXTERNAL_DIR = ROOT_DIR / "external"
WORK_DIR = ROOT_DIR / "ts_log"
LOG_DIR = ROOT_DIR / "log"

EXTERNAL_DIR.mkdir(mode=0o755, parents=True, exist_ok=True)
WORK_DIR.mkdir(mode=0o755, parents=True, exist_ok=True)
LOG_DIR.mkdir(mode=0o755, parents=True, exist_ok=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@kjps%6q(r%pd4z84)@9u=kp(@4^3b)x=fm%w$t4&r%3y#p+v5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django.contrib.humanize',
]
LOCAL_APPS = [
    'core',
    'app_root.analysis',
    'app_root.contents',
    'app_root.gameinfos',
    'app_root.helpers',
    'app_root.landing',
    'app_root.keywords',
    'modules'
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'conf.urls.local'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.admin_menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = BASE_DIR.parent / 'static'
STATICFILES_DIRS = (
    BASE_DIR / 'static',
    # path.normpath(path.join(BASE_DIR, 'static')),
    # os.path.join(BASE_DIR, "static")
)
STATIC_URL = '/dn/'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'default': {
            'class': 'logging.FileHandler',
            'filename': ROOT_DIR / "log" / "default.log",
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'default': {
            'level': 'DEBUG',
            'handlers': ['default'],
            'propagate': False,
        },
        # 'django': {
        #     'level': 'DEBUG',
        #     'handlers': ['console'],
        #     'propagate': False,
        # },
    }
}

TS_AES_KEY = bytes("Wucai6oj0sheiX3p".encode('ascii'))
TS_APP_OS = 'android'
TS_APP_DOWNLOAD_TYPE = 'township_gplay'
TS_APP_VERSION = '7.9.6'
TS_APP_COUNTRY = 'KR'

TS_APP_BVER = '7.9.6'
TS_APP_FVER = '78'

URL_CDN_PLAYRIX = 'cdn.playrix.com'
URL_CDN_TOWNSHIP = 'township-cdn.playrix.com'
URL_API_TOWNSHIP = 'township.playrix.com'

FETCH_CITY_RESP_HEADER_FILENAME = 'header.log'
FETCH_CITY_RESP_BODY_FILENAME = 'body.log'
FETCH_CITY_DECODE_JSON_FILENAME = 'decode_body.json'
FETCH_CITY_DECODE_XML_FILENAME = 'decode_data.xml'
