# Generated by Django 3.1.4 on 2020-12-30 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSaveCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='create')),
                ('update_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='update')),
                ('json_data', models.BinaryField(max_length=10000, verbose_name='json data')),
                ('xml_data', models.BinaryField(max_length=1000000, verbose_name='xml data')),
                ('ts_id', models.CharField(max_length=100, verbose_name='ts-id')),
                ('size', models.PositiveIntegerField(verbose_name='size')),
                ('memo', models.CharField(max_length=200, verbose_name='memo')),
            ],
            options={
                'verbose_name': 'Request Save City',
                'verbose_name_plural': 'Request Save City',
            },
        ),
    ]
