# Generated by Django 3.1.4 on 2020-12-30 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_time', models.PositiveIntegerField(default=None, null=True, verbose_name='build time')),
                ('building_id', models.CharField(max_length=50, verbose_name='building id')),
                ('building_name', models.CharField(max_length=50, verbose_name='building name')),
                ('order_experience', models.PositiveIntegerField(default=None, null=True, verbose_name='cash price')),
                ('cash_price', models.PositiveIntegerField(default=None, null=True, verbose_name='cash price')),
                ('coins_price', models.PositiveIntegerField(default=None, null=True, verbose_name='coins price')),
                ('level_need', models.PositiveIntegerField(default=None, null=True, verbose_name='level need')),
                ('building_type', models.PositiveSmallIntegerField(choices=[(10, 'house'), (20, 'factory'), (30, 'special factory')], verbose_name='building type')),
                ('resident', models.PositiveIntegerField(default=None, null=True, verbose_name='resident')),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='FactoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_amount', models.PositiveIntegerField(verbose_name='produce amount')),
                ('produce_time', models.PositiveIntegerField(verbose_name='produce time')),
            ],
            options={
                'verbose_name': 'factory_product',
                'verbose_name_plural': 'factory_products',
            },
        ),
        migrations.CreateModel(
            name='FactoryResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='number of products')),
            ],
            options={
                'verbose_name': 'factory_resource',
                'verbose_name_plural': 'factory_resources',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_time', models.PositiveIntegerField(default=None, null=True, verbose_name='build time')),
                ('exp', models.PositiveIntegerField(verbose_name='exp')),
                ('exp_on_train', models.PositiveIntegerField(verbose_name='exp on train')),
                ('product_id', models.CharField(max_length=50, unique=True, verbose_name='product id')),
                ('product_name', models.CharField(max_length=50, verbose_name='product name')),
                ('level_need', models.PositiveIntegerField(verbose_name='level need')),
                ('max_request', models.PositiveIntegerField(default=None, verbose_name='max request')),
                ('reward_points_each', models.PositiveIntegerField(default=None, verbose_name='reward points each')),
                ('price', models.PositiveIntegerField(default=None, verbose_name='price')),
                ('sell_price', models.PositiveIntegerField(default=None, verbose_name='sell price')),
                ('product_type', models.SmallIntegerField(choices=[(10, 'bullion'), (20, 'coins'), (30, 'feed'), (40, 'fruit'), (50, 'product'), (60, 'seed'), (100, 'material-0'), (110, 'material-1'), (120, 'material-2'), (130, 'material-3'), (140, 'material-4'), (150, 'material-5'), (160, 'material-6'), (170, 'material-7'), (180, 'material-8')], verbose_name='product type')),
                ('event', models.CharField(max_length=50, null=True, verbose_name='event')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='TownshipVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='township app version')),
                ('major', models.PositiveSmallIntegerField(verbose_name='major version')),
                ('minor', models.PositiveSmallIntegerField(verbose_name='minor version')),
                ('patch', models.PositiveSmallIntegerField(verbose_name='patch version')),
            ],
            options={
                'verbose_name': 'app version',
                'verbose_name_plural': 'app versions',
            },
        ),
        migrations.AddIndex(
            model_name='townshipversion',
            index=models.Index(fields=['version'], name='idx_version'),
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='contents.townshipversion'),
        ),
        migrations.AddField(
            model_name='factoryresource',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='factory_resources', to='contents.factoryproduct'),
        ),
        migrations.AddField(
            model_name='factoryresource',
            name='resource',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='factory_resources', to='contents.product'),
        ),
        migrations.AddField(
            model_name='factoryproduct',
            name='factory',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='factory_products', to='contents.building'),
        ),
        migrations.AddField(
            model_name='factoryproduct',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='factory_products', to='contents.product'),
        ),
        migrations.AddField(
            model_name='building',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buildings', to='contents.townshipversion'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_name'], name='idx_product_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='idx_product_type'),
        ),
    ]
