# Generated by Django 3.1.4 on 2020-12-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.BigIntegerField(db_index=True, verbose_name='address')),
                ('encoded_hex_string', models.CharField(max_length=400, verbose_name='encoded hex string')),
                ('encoded_hash', models.BigIntegerField(db_index=True, verbose_name='encoded string')),
                ('decoded_string', models.CharField(max_length=200, verbose_name='decoded string')),
                ('decoded_hash', models.BigIntegerField(db_index=True, verbose_name='decoded string')),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
            },
        ),
    ]
