# Generated by Django 3.1.4 on 2020-12-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['pk'], 'verbose_name': 'keyword', 'verbose_name_plural': 'keywords'},
        ),
    ]
